import html
head=open('/tmp/head').read(); nav=open('/tmp/nav').read().replace('ROOT','../'); foot=open('/tmp/foot').read()
def page(slug,title,desc,kicker,lede,meta,body,figma):
    m=''.join(f'<div><span class="mono">{k}</span><b>{v}</b></div>' for k,v in meta)
    return f'''<!doctype html><html lang="en"><head>
{head}
<title>{title} — Kaushik Subramaniam</title><meta name="description" content="{html.escape(desc)}">
<link rel="stylesheet" href="../styles.css"></head><body>
<div class="shell">{nav}</div><main class="cs"><div class="wrap">
<div class="cs-hero"><a class="back rv" href="../#work">← All work</a>
<div class="rv" style="margin-top:36px"><span class="mono">{kicker}</span></div>
<h1 class="rv" style="max-width:18ch">{title}</h1><p class="lede rv">{lede}</p>
<div class="meta rv">{m}</div><div class="cs-cover rv"><img src="../assets/{slug}.jpg" alt="{title} product screen"></div></div>
<div class="read">{body}
<section class="rv"><span class="mono">Full deck</span><h2>See the complete case study</h2><p>Every screen, flow and artifact lives in the Figma presentation.</p><a class="btn primary figma" href="{figma}" target="_blank" rel="noopener">Open the full deck in Figma ↗</a></section>
</div></div></main>
{foot}
<script src="../main.js"></script></body></html>'''
def sec(n,label,h,inner): return f'<section class="rv"><span class="mono">{n} — {label}</span><h2>{h}</h2>{inner}</section>'
P=lambda *ps:''.join(f'<p>{p}</p>' for p in ps)
cards=lambda cs:'<div class="cards">'+''.join(f'<div class="card"><h4>{a}</h4><p>{b}</p></div>' for a,b in cs)+'</div>'
hmw=lambda qs:'<ol class="hmw">'+''.join(f'<li>{q}</li>' for q in qs)+'</ol>'
checks=lambda xs:'<ul class="checks">'+''.join(f'<li>{x}</li>' for x in xs)+'</ul>'
metrics=lambda ms:'<div class="metrics">'+''.join(f'<div class="metric"><b>{a}</b><span>{b}</span></div>' for a,b in ms)+'</div>'
def matrix(q): return '<div class="matrix">'+''.join(f'<div class="{"hi" if hi else ""}"><span class="mono">{a}</span><p>{b}</p></div>' for a,b,hi in q)+'</div>'

qa_body=''.join([
sec('01','Overview','Creating a foundation',P("I led the end-to-end design for Quick Automations, a real-time automation framework built for conversational support workflows inside Freshdesk Omni.","From defining the information architecture to turning highly technical automation logic into approachable templates, I worked closely with Product, Engineering, CX and GTM teams on an experience that could support omni-channel workflows without overwhelming admins.","The project became a foundational step toward Freshdesk's long-term workflow modernization vision.")),
sec('02','Problem','Built for email. Strained by chat.',P("Freshdesk's legacy automation framework was designed for email-first support. It relied on <b>Hourly Triggers</b>, which evaluate tickets periodically instead of instantly. That worked for email, but it was a major limitation on conversational channels where customers expect replies in seconds.")+checks(["Instant acknowledgements","Delay-based customer reassurance","Faster SLA-driven workflows","Multi-channel orchestration"])+P("Meanwhile Zendesk and Intercom already supported second-level conversational automation. Real-time execution had become something customers expected, not a premium extra.")),
sec('03','How might we','Three questions, one north star.',hmw(["Help support teams automate real-time conversations without complex setup?","Execute automation rules within seconds instead of hours?","Simplify conversational automation for SMB admins while supporting omni-channel scale?"])),
sec('04','Research','Why the existing system kept falling short.',P("Research with <b>18 CX operations leads</b> showed that <b>94%</b> of teams expected automated acknowledgements within 30–90 seconds on chat channels.")+cards([("Email-first architecture","Tickets were evaluated periodically. That was reliable for email but unfit for channels that need instant responses."),("Expectations had changed","Delays directly hurt CSAT and SLA on chat-based channels."),("Delay & cancel became critical","Automations had to stop if an agent replied first. Without that, customers got duplicate or irrelevant replies."),("Builders were too complex","Templates averaged 2.3 minutes to set up vs 8.7 for builders. Errors dropped from 2.4 to 0.2 per setup.")])),
sec('05','Behaviour',"Admins didn't want to build workflows.",'<blockquote>“Admins didn\'t want to build workflows. They wanted the system to intelligently handle operational gaps automatically.”</blockquote>'+P("Email automations were treated as long-term process configuration. Conversational automations were expected to be set up and deployed within minutes, often during live support shifts. That pushed us to prioritize guided templates over fully customizable builders.")),
sec('06','Solution','Six high-frequency gaps. Six templates.',cards([("Keep customers informed of delays","Sends reassurance messages that auto-cancel if an agent replies first."),("Reassign to available agent","Reroutes chats when the assigned agent doesn't respond in time."),("Reroute to fallback group","Moves conversations to backup groups during peak load."),("Follow up with inactive customers","Nudges customers who stop responding mid-conversation."),("Reduce load","Changes ticket status when customers stay inactive, which clears the queue."),("Track resolution delays","Tags tickets like <i>SLA risk</i> once they pass a wait threshold.")])),
sec('07','Competitors','A strategic bridge to real-time.',P("Zendesk, Zoho, Salesforce and Intercom all relied on block-based builders that take significant setup. Freshdesk had no modern builder, and Hourly Triggers couldn't meet 30-second SLAs. Quick Automations became the bridge from legacy email-first automation to real-time orchestration.")),
sec('08','Prioritisation','Mapping value against effort.',matrix([("High impact · Low effort","Instant acknowledgement replies, follow-ups with inactive customers",1),("High impact · High effort","Template-based automation, delay-and-cancel logic, multi-channel auto-replies",1),("Low impact · Low effort","Cosmetic setup tweaks",0),("Low impact · High effort","Fully customizable workflow builder",0)])),
sec('09','Shipped','What went out the door.',cards([("Instant automation engine","Runs workflows in as little as 30 seconds, separated from legacy Hourly Triggers."),("Multi-channel","Configure once across WhatsApp, Facebook DM, Instagram DM and Web Chat."),("Guided templates","Onboarding takes minutes, not afternoons."),("Delay & cancel","Automations stop the moment an agent responds.")])),
sec('10','Impact','Measuring impact.',metrics([("75%","of real-time channel customers configured Quick Automations"),("85%","coverage of eligible conversational workflows"),("91%","reduction in dropped conversations"),("$120K","feature-attributed MRR across 99 paid accounts")])+P("Quick Automations laid the foundation for Freshdesk's unified <b>Workflows</b> platform, which brings real-time and asynchronous automation into one orchestration layer.")),
])
qc_body=''.join([
sec('01','Overview','Inside the composer.',P("I designed the end-to-end experience for <b>Quality Coach</b>, an AI assistance layer built into the agent reply composer.","The goal was to help agents keep conversations high-quality in real time without disrupting their flow. Working with Product, AI, Engineering and CX, the challenge was to surface AI feedback in context while keeping suggestions actionable rather than overwhelming, so agents still felt in control.")),
sec('02','Problem','Audited after the fact. Coached too late.',P("Traditional QA relied on audits after the conversation ended, so feedback arrived only once the interaction was already over.")+checks(["Agents repeated avoidable mistakes","Quality feedback arrived too late","QA teams spent excessive time auditing manually","Service quality varied between agents","Managers lacked real-time visibility"])),
sec('03','How might we','Three questions, one north star.',hmw(["Help agents improve conversation quality in real time without disrupting live interactions?","Reduce dependency on post-conversation audits through proactive AI?","Surface contextual AI feedback without overloading agents?"])),
sec('04','Research','Why traditional QA kept missing the moment.',cards([("Reactive","Audits surfaced patterns but rarely helped in the moment mistakes happened."),("Overload","Tone and grammar slipped across parallel chats. The cause was cognitive load, not a lack of knowledge."),("Friction","Agents ignored intrusive suggestions. Concise, contextual feedback won."),("Collaborative AI","Agents preferred assistive AI to autonomous AI. They wanted to own the reply.")])),
sec('05','Behaviour',"Agents didn't want another reviewer.",'<blockquote>“They wanted intelligent assistance that helped them respond better without interrupting their flow.”</blockquote>'+P("That insight is why Quality Coach lives inside the reply composer rather than in a separate review interface.")),
sec('06','Solution','An assistance layer, not an audit tool.',P("Quality Coach evaluates replies as they're written and surfaces suggestions across seven dimensions: tone, grammar, profanity, sentence length, relevancy, spelling and filler words. Agents can apply each one instantly or ignore it.")),
sec('07','Competitors','A coaching layer no one else built.',P("Intercom, Zendesk, Salesforce Service Cloud, Grammarly Business and Kore.ai either focused on post-conversation QA or offered generic writing help disconnected from support workflows. Almost none offered contextual coaching inside the reply itself.")),
sec('08','Prioritisation','Mapping coaching opportunities.',matrix([("High impact · High effort","Inline grammar, real-time tone & profanity analysis, contextual relevancy engine",1),("High impact · Low effort","Filler-word nudges",1),("Low impact · Low effort","Overall reply score, urgent-issue hints",0),("Low impact · High effort","Auto-rewriting full replies, mandatory AI approval gating",0)])),
sec('09','Shipped','What went out the door.',cards([("Real-time coaching","Recommendations arrive before the message is sent."),("Inline suggestions","Tone, grammar, profanity, length, relevancy and spelling, right in the composer."),("One-tap corrections","Apply or dismiss. The agent always owns the reply."),("QA visibility","Managers see how coaching is working while shifts are live.")])),
sec('10','Impact','Measuring impact.',metrics([("62%","reduction in repeated grammar, tone & profanity issues"),("+18 pts","CSAT lift during high-volume shifts"),("47%","less time spent by QA manually auditing routine conversations"),("92%","of agents kept Quality Coach on after the two-week trial")])+P("Quality Coach laid the foundation for Freshdesk Omni's broader AI copilot vision.")),
])
open('work/quick-automations.html','w').write(page('qa','Quick Automations',"Real-time automation for conversational support in Freshdesk Omni.",'Freshdesk Omni · 0→1 · 2025',"An instant automation framework for conversational support, running workflows in as little as 30 seconds across WhatsApp, Web Chat, Facebook DM and Instagram DM.",[("Role","Senior Product Designer"),("Scope","Research · Strategy · UI/UX"),("Team","PM, Eng, CX, GTM"),("Year","2025")],qa_body,"https://www.figma.com/design/UclYCfmKbdCuBM0G80xIAt/Presentations.?node-id=84576-9446"))
open('work/quality-coach.html','w').write(page('qc','Quality Coach',"Real-time AI coaching inside the Freshdesk Omni reply composer.",'Freshdesk Omni · AI-first CX · 2024',"An AI-powered real-time coaching system that helps support agents improve grammar, tone and clarity while they're replying to customers.",[("Role","Senior Product Designer"),("Scope","Research · Product · UX/UI"),("Team","PM, AI, Eng, CX"),("Year","2024")],qc_body,"https://www.figma.com/design/UclYCfmKbdCuBM0G80xIAt/Presentations.?node-id=84610-23531"))
