import html
head=open('/tmp/head').read(); nav=open('/tmp/nav').read().replace('ROOT','../'); foot=open('/tmp/foot').read().replace('ROOT','../index.html')
AST='<span class="x-ast" aria-hidden="true">✱</span>'
ARR='<span class="x-arr" aria-hidden="true">→</span>'

def page(c):
    meta=''.join(f'<div><span class="mono">{k}</span><b>{v.replace(" · ","<br>") if k=="Role" else v}</b></div>' for k,v in c['meta'])
    t1,t2=c['title']; title=f"{t1} {t2.rstrip('.')}"
    body=''.join(sec(i,s) for i,s in enumerate(c['sections'],1))
    return f'''<!doctype html><html lang="en"><head>
{head}
<title>{title} — Kaushik Subramaniam</title><meta name="description" content="{html.escape(c['desc'])}">
<link rel="stylesheet" href="../styles.css"></head><body>
<div class="shell">{nav}</div><main class="cs"><div class="csx">
<div class="wrap"><div class="cs-hero"><a class="back rv" href="../index.html">← Home</a>
<div class="rv" style="margin-top:36px"><span class="mono">{c['kicker']}</span></div>
<h1 class="rv">{title}</h1><p class="lede rv">{c['lede']}</p>
<div class="meta rv">{meta}</div><div class="cs-cover rv"><img src="../assets/{c['slug']}.jpg" alt="{title}: {c['coveralt']}"></div></div></div>
{looks(c)}
<div class="wrap"><div class="read">{body}</div>
{nextcta(c)}
<div class="cs-foot"><span>© 2026 Kaushik Subramaniam M</span></div></div>
</div></main>
<script src="../main.js"></script></body></html>'''

def nextcta(c):
    n=c['next']; t1,t2=n['title']
    return f'''<a class="x-next rv" href="{n['file']}"><span class="x-next-txt"><span class="x-k">Next project</span><span class="x-next-t">{t1} {t2.rstrip('.')}</span><span class="x-next-d">{n['desc']}</span><span class="x-next-go">View project <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg></span></span><span class="x-next-img"><img src="../assets/{n['slug']}.jpg" alt="" loading="lazy"></span></a>'''

def looks(c):
    slug,caps=c['slug'],c['caps']; n=len(caps)
    def fig(i,cap,dup):
        hid=' aria-hidden="true"' if dup else ''
        alt='' if dup else f"{c['name']}: {cap}"
        return f'<figure class="wl-item"{hid}><span class="wl-img"><img src="../assets/screens/{slug}-{i}.jpg" alt="{alt}" loading="lazy"></span><figcaption><span>{i:02d} / {n:02d}</span>{cap}</figcaption></figure>'
    one=''.join(fig(i,cp,False) for i,cp in enumerate(caps,1)); two=''.join(fig(i,cp,True) for i,cp in enumerate(caps,1))
    return f'<section class="wl rv" aria-label="What it looks like"><div class="x-wlhead"><span class="x-k">What it looks like · {c["name"]}</span><span class="x-k">Hover to pause</span></div><div class="wl-view"><div class="wl-track">{one}{two}</div></div></section>'

def sec(i,s):
    if s.get('wide'):
        return f'<section class="x-wide rv"><span class="x-k">{s["label"]}</span><h2>{s["h"]}</h2>{"".join(blk(b) for b in s["blocks"])}</section>'
    return f'<section class="x-sec rv"><div class="x-lab"><span class="x-k">{s["n"]} — {s["label"]}</span></div><div class="x-body"><h2>{s["h"]}</h2>{"".join(blk(b) for b in s["blocks"])}</div></section>'

def blk(b):
    k=b[0]
    if k=='p': return ''.join(f'<p>{x}</p>' for x in b[1:])
    if k=='grid6': return '<ol class="x-pts">'+''.join(f'<li><span class="x-i">{i:02d}</span><span>{x}</span></li>' for i,x in enumerate(b[1],1))+'</ol>'
    if k=='hmw': return '<ol class="hmw">'+''.join(f'<li>{x}</li>' for x in b[1])+'</ol>'
    if k=='rows': return '<div class="cards">'+''.join(f'<div class="card"><span class="x-n">{cat}</span><h4>{t}</h4><p>{d}</p></div>' for cat,t,d in b[1])+'</div>'
    if k=='ast': return f'<div class="take x-take"><h4>{b[1]}</h4><ol class="x-rows">'+''.join(f'<li><span class="x-i">{i:02d}</span><span>{x}</span></li>' for i,x in enumerate(b[2],1))+'</ol></div>'
    if k=='quote': return f'<figure class="x-quote"><figcaption class="x-k">✦ Key insight</figcaption><blockquote>{b[1]}</blockquote></figure>'
    if k=='twocol':
        a=''.join(f'<li>{x}</li>' for x in b[2]); f=''.join(f'<li>{x}</li>' for x in b[4])
        return f'<div class="twocol"><div><h4>{b[1]}</h4><ol>{a}</ol></div><div><h4>{b[3]}</h4><ol>{f}</ol></div></div>'
    if k=='templates': return '<div class="cards">'+''.join(f'<div class="card"><span class="x-n">{b[2]} {i:02d}</span><h4>{t}</h4><p>{d}</p></div>' for i,(t,d) in enumerate(b[1],1))+'</div>'
    if k=='insights': return f'<div class="take"><h4>{b[1]}</h4></div><div class="cards x-ins2">'+''.join(f'<div class="card"><h4>{t}</h4><p>{d}</p></div>' for t,d in b[2])+'</div>'
    if k=='edge': return '<div class="edge"><h4>Our edge</h4><ul>'+''.join(f'<li>{x}</li>' for x in b[1])+'</ul></div>'
    if k=='dims': return '<ol class="dims">'+''.join(f'<li><span>{i:02d}</span>{x}</li>' for i,x in enumerate(b[1],1))+'<li class="x-always"><span>Plus</span>Always on</li></ol>'
    if k=='matrix':
        def cell(q):
            name,sub,items,hot=q
            its=''.join(f'<li><b>{t}</b>{f" <span>{d}</span>" if d else ""}</li>' for t,d in items)
            return f'<div class="{"hot" if hot else ""}"><span class="mono">{name}</span><ul>{its}</ul></div>'
        return ('<div class="x-graph"><div class="g-yax"><span>High</span><b>Impact</b><span>Low</span></div>'
                '<div class="matrix x-matrix">'+''.join(cell(q) for q in b[1])+'</div>'
                '<div class="g-xax"><span>Low</span><b>Effort</b><span>High</span></div></div>')
    if k=='shots': return '<div class="x-shots">'+''.join(f'<figure><span class="x-shot"><img src="../assets/screens/{src}.jpg" alt="{cap}" loading="lazy"></span><figcaption class="x-k">{cap}</figcaption></figure>' for src,cap in b[1])+'</div>'
    if k=='features':
        n=len(b[1])
        return '<div class="x-scards">'+''.join(f'<div class="x-scard" style="--i:{i-1}"><div class="x-sc-in"><div class="x-sc-t"><span class="x-n">Feature {i:02d} <em>/ {i:02d} of {n:02d}</em></span><h3>{t}</h3><p>{d}</p></div><span class="x-shot"><img src="../assets/screens/{img}.jpg" alt="{t} screen" loading="lazy"></span></div></div>' for i,(t,d,img) in enumerate(b[1],1))+'</div>'
    if k=='numbers':
        return '<div class="x-ngrid">'+''.join(f'<div class="x-ncard{" x-wide2" if len(x)>2 else ""}"><b>{x[0]}</b><p>{x[1]}</p></div>' for x in b[1])+'</div>'
    raise ValueError(k)

QA=dict(slug='qa',name='Quick Automations',title=('Quick','Automations.'),endk='Freshdesk Omni · 2025',
desc="Real-time automation for conversational support in Freshdesk Omni.",kicker='Freshdesk Omni · 0→1',
lede="An instant automation framework built for conversational support inside Freshdesk, executing workflows in as little as <b>30 seconds</b> across WhatsApp, Web Chat, Facebook DM and Instagram DM.",
meta=[("Project type","0→1 Product Experience"),("Role","Research · Product Thinking · UX Strategy"),("Surface","Freshdesk Omni")],coveralt="the Quick Automations rule list with the delay rule configuration",
caps=["Quick Automations home","Multi-channel setup","Template gallery","Rule configuration","Rule enablement"],
sections=[
dict(n='01',label='Creating a foundation',h='My role',blocks=[('p',"I led the end-to-end design for Quick Automations, a real-time automation framework built specifically for conversational support workflows inside Freshdesk Omni.","From defining the information architecture to simplifying highly technical automation logic into approachable templates, I worked closely with Product, Engineering, CX and GTM teams to shape a scalable experience that could support omni-channel workflows without overwhelming admins.","<b>The project eventually became a foundational step toward Freshdesk's long-term workflow modernization vision.</b>")]),
dict(n='02',label='Problem statement',h='Built for email.<br>Strained by chat.',blocks=[('p',"Freshdesk's legacy automation framework was originally designed for email-first support workflows. The system relied heavily on Hourly Triggers: tickets were evaluated periodically instead of instantly. While this worked for email, it became a major operational limitation for conversational channels where customers expect responses in seconds."),('grid6',["Instant acknowledgements","Delay-based customer reassurance","Smart fallback routing","Real-time follow-ups","Faster SLA-driven workflows","Multi-channel orchestration"]),('p',"Meanwhile competitors like Zendesk and Intercom already supported second-level conversational automation, making real-time execution a market expectation rather than a premium capability.")]),
dict(n='03',label='How might we',h='Three questions,<br>one north star.',blocks=[('hmw',["How might we help support teams automate real-time conversations without complex setup?","How might we execute automation rules within seconds instead of hours?","How might we simplify conversational automation for SMB admins while supporting omni-channel scale?"])]),
dict(wide=True,label='Current state · Hourly triggers',h='The legacy automation surface, built for asynchronous email workflows.',blocks=[('shots',[('qa-legacy-1','Hourly trigger list'),('qa-legacy-2','Trigger conditions')])]),
dict(n='04',label='Research',h='Why the existing system kept falling short.',blocks=[('p',"Before designing Quick Automations, I needed to understand why Freshdesk's existing framework struggled with conversational workflows. The findings validated the need for a dedicated real-time layer and revealed how dramatically customer expectations had shifted."),('rows',[("Architecture","Email-first automation architecture","Freshdesk's legacy system was built around asynchronous workflows. Tickets were evaluated periodically via Hourly Triggers: reliable for email, but unfit for channels demanding instant responsiveness."),("Expectation","Real-time expectations had changed","Research with 18 CX operations leads revealed 94% of teams expected automation-driven acknowledgements within 30–90 seconds for chat-based channels. Delays directly impacted CSAT and SLA."),("Logic","Delay & cancel logic became critical","Conversational support required automations to dynamically stop if an agent responded before the threshold. Existing systems lacked this, creating duplicate or irrelevant replies after agents had already engaged."),("Complexity","Workflow builders were too complex","Template-based setup averaged 2.3 minutes vs 8.7 for builders. Configuration errors dropped from 2.4 to 0.2 per setup, strongly validating a template-first experience."),("Priority","Speed mattered more than flexibility","Teams consistently prioritized faster setup, faster execution and faster acknowledgement over highly customizable but operationally complex workflow systems.")]),('ast','Key takeaways',["Real-time channels require second-level automation responsiveness","Traditional automation models fail for conversational workflows","Delay-and-cancel execution is critical for chat-based support","Users preferred guided templates over complex workflow builders","Conversational automation required a fundamentally different execution architecture"])]),
dict(n='05',label='Deep dive into user behaviour',h="Admins didn't want<br>to build workflows.",blocks=[('p',"Through stakeholder interviews, workflow analysis and operational mapping, one insight kept surfacing: conversational support teams behaved very differently from email-first teams. They needed instant fallback workflows, automated reassurance, fast setup, and a single place to manage multi-channel automations."),('quote',"“<em>Admins didn't want to build workflows.</em> They wanted the system to intelligently handle operational gaps automatically.”"),('p',"While email automations were treated as long-term process configurations, conversational automations were expected to be configured and deployed within minutes, often during active support shifts. This heavily influenced the decision to prioritize guided templates over fully customizable workflow builders."),('twocol','Research objectives',["Understand operational gaps in conversational support workflows","Identify limitations in the existing automation system","Understand execution speed expectations for real-time channels","Reduce setup complexity for SMB admins","Explore scalable patterns for future workflow unification"],'Key findings',["Customers expected automation execution within seconds, not minutes","Most urgent use cases revolved around delayed responses and fallback routing","Existing automation systems felt too technical for SMB admins","Template-based setup significantly reduced onboarding friction","Real-time automation created immediate operational value","Multi-channel conversational support increased automation relevance significantly"])]),
dict(n='06',label='The 6 templates',h='Six high-frequency operational gaps. Six templates.',blocks=[('p',"To simplify setup for SMB and mid-market admins, I designed Quick Automations around guided templates instead of requiring users to configure workflows from scratch. Each template focused on a high-frequency operational gap observed during research."),('templates',[("Keep customers informed of delays","Sends reassurance messages when agents take longer than expected. Uses delay-and-cancel logic so messages auto-cancel if an agent replies first."),("Reassign to available agent","Unassigns and reroutes conversations when the assigned agent fails to respond within a set duration, preventing chats from getting stuck."),("Reroute to fallback group","Moves conversations to backup support groups during peak load, helping teams maintain SLA commitments through traffic spikes."),("Follow up with inactive customers","Sends nudges when customers stop responding mid-conversation, reviving stalled chats without manual effort."),("Reduce load for agents","Automatically changes ticket status when customers remain inactive, clearing queues and freeing agents for fresh conversations."),("Keep track of resolution delays","Automatically tags tickets that remain unresolved beyond a set time, surfacing SLA risks and queue delays so teams can intervene before resolution times slip. Admins set a wait threshold, then assign or remove tags like SLA risk or waiting_in_queue.")],'Template')]),
dict(n='07',label='Competitor analysis',h='A strategic bridge to real-time.',blocks=[('p',"I analyzed conversational automation across Zendesk, Zoho, Salesforce and Intercom. While each offered powerful systems, all relied on block-based builders requiring extensive setup. Freshdesk had no modern builder yet, and its Hourly Triggers couldn't meet 30-second SLAs.","Quick Automations became a strategic bridge between <b>legacy email-first automations</b> and <b>future real-time workflow orchestration</b>."),('insights','Key market insights',[("Workflow builders prioritized flexibility over speed","Most competitors optimized for highly customizable systems, but configuring even simple conversational workflows required multiple setup steps and technical understanding."),("Conversational support was rapidly becoming the norm","Volume across WhatsApp, social DMs, web chat and omni-channel systems was growing significantly faster than email, increasing the need for real-time operational tooling."),("SMB teams needed simpler automation experiences","Existing workflow systems were too complex for smaller support teams. A clear opportunity existed to simplify setup through guided operational templates."),("Legacy automation was built for asynchronous support","Traditional architectures evaluated tickets periodically rather than instantly, poorly optimized for conversational support where execution speed directly impacts CX.")]),('edge',["Instant rule execution in as little as 30 seconds","Template-first conversational automation","Real-time delay-and-cancel workflows","Multi-channel support orchestration","Simplified setup for SMB admins"]),('p',"Instead of overwhelming users with fully customizable workflow builders, we optimized for speed, usability, operational clarity and faster time-to-value.")]),
dict(n='08',label='Action / Impact analysis',h='Mapping value against effort.',blocks=[('p',"We mapped each automation opportunity using an Impact / Effort matrix to identify workflows that created the highest operational value with minimal setup friction for support teams.","The exercise helped us prioritize features that could immediately improve conversational support responsiveness while flagging larger infrastructure investments for the next phase of the workflow platform."),('matrix',[("Easy wins","High impact · Low effort",[("Instant acknowledgement replies",""),("Follow up with inactive customers","")],False),("Big bets","High impact · High effort",[("Template based automation",""),("Delay-and-cancel logic",""),("Multi-channel auto-replies","")],True),("Incremental","Low impact · Low effort",[("Template customization","")],False),("Money pit","Low impact · High effort",[("Fully customizable workflow builder","")],False)]),('ast','Findings',["Simple conversational automations created the fastest operational impact. They solved immediate support-team pain points without heavy configuration.","High-frequency workflows like acknowledgement replies and inactive customer follow-ups delivered significantly higher perceived value than advanced workflow customization.","Larger investments like the real-time execution engine and delay/cancel architecture were foundational in enabling future workflow scalability across omni-channel support."],True)]),
dict(n='09',label='Features shipped',h='What we built.',blocks=[('features',[("Instant Automation Engine","A lightweight framework executing workflows in as little as 30 seconds. Architecturally separated from legacy Hourly Triggers to deliver second-level reliability.","qa-1"),("Multi-channel quick automations","Configure conversational automations once across WhatsApp, Facebook DM, Instagram DM and Web Chat, collapsing setup effort for omni-channel teams.","qa-2"),("Template-based setup","Guided templates for delays, reassignment, fallback routing, follow-ups and load reduction. Onboarding measured in minutes, not afternoons.","qa-3"),("Delay & cancel logic","Automations halt the moment an agent responds, eliminating duplicate messages and conversational noise.","qa-wb-4")])]),
dict(n='10',label='Measuring impact',h='The numbers.',blocks=[('numbers',[("75%","of real-time channel customers configured Quick Automations"),("85%","coverage of eligible conversational workflows across channels"),("91%","reduction in dropped conversations via instant acknowledgements"),("$120K","in feature-attributed MRR across 99 paid accounts")]),('p',"Beyond the metrics, Quick Automations established the foundation for Freshdesk's future unified <b>“Workflows” platform</b>, combining both real-time and asynchronous automation systems within one orchestration layer.")]),
dict(n='11',label="What's next",h='A product is never finished.',blocks=[('p',"Quick Automations was designed as the first step toward a broader workflow modernization initiative. The long-term vision unifies legacy Automations and Quick Automations under a single Workflows platform, capable of handling both asynchronous and real-time support automation within one scalable orchestration system.","The next phase focuses on richer automation actions, smarter execution, expanded orchestration and eventually a modern block-based builder, while preserving the simplicity and speed that made Quick Automations effective for conversational support.")]),
])

QC=dict(slug='qc',name='Quality Coach',title=('Quality','Coach.'),endk='Freddy AI · 2024',
desc="Real-time AI coaching inside the Freshdesk Omni reply composer.",kicker='Freshdesk Omni · AI-first CX',
lede="An AI-powered real-time coaching system built inside Freshdesk Omni, helping support agents improve <b>grammar, tone and clarity</b> while they're actively replying to customers.",
meta=[("Project type","AI-first CX experience"),("Role","Research · Product Thinking · UX Strategy"),("Surface","Freshdesk Omni")],coveralt="the reply composer with an inline grammar suggestion",
caps=["Live coaching","Profanity correction","Grammar correction","All errors","Usage analytics"],
sections=[
dict(n='01',label='Creating a foundation',h='My role',blocks=[('p',"I worked on designing the end-to-end experience for <b>Quality Coach</b>, an AI-powered assistance layer integrated directly within the agent reply composer.","The project focused on helping support agents maintain high-quality customer interactions in real time without disrupting their workflow. I collaborated closely with Product, AI, Engineering and CX stakeholders to simplify how AI-generated feedback could be surfaced contextually while keeping suggestions actionable rather than overwhelming.","A major part of the challenge involved balancing proactive AI assistance with conversational flow so agents still felt in control of responses.")]),
dict(n='02',label='Problem statement',h='Audited after the fact. Coached too late.',blocks=[('p',"Customer support teams often struggle to maintain consistent service quality across large volumes of conversations, especially during high-pressure support periods. Traditional QA systems primarily relied on post-conversation audits where feedback was shared after interactions had already concluded, creating several operational gaps:"),('grid6',["Agents repeated avoidable mistakes","Quality feedback arrived too late","QA teams spent excessive time auditing manually","Service quality varied significantly between agents","Managers lacked real-time visibility into quality","Coaching loops never closed during live shifts"]),('p',"Support teams needed a proactive quality system capable of helping agents improve conversations while they were actively responding to customers.")]),
dict(n='03',label='How might we',h='Three questions,<br>one north star.',blocks=[('hmw',["How might we help support agents improve conversation quality in real time without disrupting active customer interactions?","How might we reduce dependency on post-conversation audits through proactive AI assistance?","How might we surface contextual AI feedback without overwhelming agents cognitively during live conversations?"])]),
dict(n='04',label='Research',h='Why traditional QA kept missing the moment.',blocks=[('p',"Before designing Quality Coach, I wanted to understand how support teams currently handled quality assurance and where operational inefficiencies emerged inside existing workflows. The research focused on agent behaviour during live conversations, post-conversation QA processes, feedback fatigue, AI-assisted writing behaviour and real-time coaching expectations."),('rows',[("Reactive","Traditional QA was reactive","Most quality systems evaluated conversations after they ended. Audits surfaced patterns but rarely helped agents during the moments where mistakes actually happened."),("Overload","Agents struggled at peak volume","Tone, grammar and compliance slipped while handling multiple chats at once. The issue wasn't knowledge, it was cognitive overload."),("Friction","Too much feedback created friction","Agents quickly ignored systems that generated excessive or intrusive suggestions. Concise, contextual feedback outperformed long-form correction."),("Visibility","Managers lacked live visibility","QA managers could only spot patterns after conversations finished. Teams needed live operational visibility, not retrospective analysis alone."),("Collaboration","AI had to feel collaborative","Agents preferred assistive AI over autonomous AI. They wanted suggestions while still owning the final response, a foundational principle for the design.")]),('ast','Key takeaways',["Quality improvement needed to happen during conversations, not after","Lightweight contextual suggestions beat intrusive AI interventions","Cognitive overload was a bigger problem than lack of training","Real-time coaching meaningfully reduced repetitive QA effort","AI worked best when agents kept response ownership"])]),
dict(n='05',label='Deep dive into user behaviour',h="Agents didn't want another reviewer.",blocks=[('p',"Through workflow analysis, stakeholder discussions and support interaction reviews, I observed clear behavioural patterns across agents and QA teams. Agents focused heavily on speed and resolution, unintentionally overlooking tone consistency, grammar quality or conversational clarity during busy periods. QA managers, on the other hand, spent significant time manually auditing conversations after completion while recurring quality issues kept repeating across interactions."),('quote',"“<em>Agents didn't want another tool to review them.</em> They wanted intelligent assistance that helped them respond better without interrupting their flow.”"),('p',"This became the foundation for embedding Quality Coach directly inside the reply composer instead of creating a separate review interface."),('twocol','Research objectives',["Understand operational gaps in traditional QA workflows","Identify moments where agents commonly make mistakes","Reduce cognitive overload during conversations","Explore how AI suggestions could feel contextual instead of intrusive","Improve conversation quality without increasing handling time"],'Key findings',["Real-time guidance was significantly more valuable than post-conversation feedback","Concise suggestions performed better than long-form AI corrections","Agents preferred contextual inline recommendations","QA managers wanted operational visibility into coaching effectiveness","Conversation quality improved when AI feedback was actionable and immediate"])]),
dict(n='06',label='Solution overview',h='An assistance layer, not an audit tool.',blocks=[('p',"Quality Coach introduced a proactive AI assistance layer directly within the agent reply experience. The system continuously evaluated replies in real time and surfaced contextual quality suggestions across seven dimensions, either applied instantly or ignored entirely. Agents stayed in control while still benefiting from AI-powered coaching."),('dims',["Grammar","Tone","Sentence length","Profanity","Relevancy","Filler words","Spelling"])]),
dict(n='07',label='Competitor analysis',h='A coaching layer no one else built.',blocks=[('p',"I analyzed conversational quality and AI assistance experiences across Intercom, Zendesk, Salesforce Service Cloud, Grammarly Business and Kore.ai. Most platforms either focused heavily on post-conversation QA reviews or provided generic writing assistance disconnected from customer support workflows. Very few systems offered deeply contextual conversational coaching directly embedded inside the support reply experience."),('insights','Key market insights',[("Support teams were shifting toward AI-assisted operations","CX organizations increasingly expected AI to proactively improve agent productivity and quality, not just function as passive analytics."),("QA teams were overwhelmed by manual audits","Traditional QA workflows scaled poorly as conversation volumes increased, putting operational pressure on quality managers."),("Real-time assistance had stronger behavioural impact","Immediate feedback created higher correction rates compared to delayed audit-based coaching, across every cohort we studied."),("AI systems needed to remain assistive","Support agents responded more positively to collaborative AI that enhanced responses instead of replacing them entirely.")]),('edge',["Real-time contextual AI coaching","Inline conversational quality analysis","Lightweight assistive suggestions","Actionable feedback over generic scoring","Embedded composer experience"])]),
dict(n='08',label='Action / Impact analysis',h='Mapping coaching opportunities.',blocks=[('p',"We mapped coaching opportunities using an Impact / Effort framework to identify which AI interventions created the highest improvement in conversation quality without disrupting agents during live interactions."),('matrix',[("Easy wins","High impact · Low effort",[("Inline grammar correction","Real-time inline grammar fixes during the live composer flow."),("Filler-word reduction","Lightweight nudges to remove filler words from agent responses.")],False),("Big bets","High impact · High effort",[("Real-time tone and profanity analysis","Continuously evaluate tone with on-demand Freddy API calls from the composer."),("Contextual relevancy engine","Detect off-topic replies based on conversation context.")],True),("Incremental","Low impact · Low effort",[("Extended analysis","Calculating an overall reply score to gauge performance."),("Partial resolve","Suggest solving issues that need immediate attention.")],False),("Money pit","Low impact · High effort",[("Auto-rewriting full replies","Removes agent autonomy and costs too many tokens."),("Mandatory AI approval gating","Disrupts active conversations and increases handle time.")],False)]),('ast','Key takeaways',["Lightweight inline coaching created significantly better adoption than disruptive review-based systems","Contextual suggestions improved agent confidence without increasing cognitive overload","Real-time intervention reduced repetitive quality issues before conversations reached QA audits"])]),
dict(n='09',label='Features shipped',h='What we built.',blocks=[('features',[("Real-time quality coaching","An AI-powered coaching layer that continuously analyzed agent responses during active customer conversations and surfaced immediate quality recommendations, so agents could improve responses before messages were sent.","qc-1"),("Contextual inline suggestions","Suggestions for tone, grammar, profanity, sentence length, relevancy and spelling appeared directly within the reply composer, reducing workflow interruption.","qc-3"),("Actionable AI corrections","Every suggestion could be applied in one tap or ignored entirely, so agents fixed issues without leaving the composer and always kept ownership of the reply.","qc-wb-3"),("QA visibility & analytics","Managers could track coaching adoption, accepted and ignored suggestions, and CSAT and quality scores with and without Quality Coach, without waiting for audits.","qc-5")])]),
dict(n='10',label='Measuring impact',h='The numbers.',blocks=[('numbers',[("62%","reduction in repeated grammar, tone & profanity issues across agents"),("47%","drop in time spent by QA teams auditing routine conversations manually"),("+18 pts","lift in CSAT score during high-volume shifts where Quality Coach was active"),("92%","of agents kept Quality Coach enabled after the first two-week trial"),("Positive sentiment","Analytics showed customer sentiment stayed closer to positive at all times when agents used Quality Coach to handle conversations","x-span2")],'x-nums3'),('p',"Beyond the metrics, Quality Coach established the foundation for Freshdesk Omni's broader AI copilot vision, combining real-time coaching, conversational intelligence and QA visibility within one assistive layer.")]),
dict(n='11',label="What's next",h='A product is never finished.',blocks=[('p',"Quality Coach was designed as an early foundational layer for AI-assisted customer support experiences inside Freshdesk Omni. The long-term vision extends beyond grammar and tone correction toward fully contextual conversational intelligence, capable of proactively improving resolution quality, compliance adherence, empathy and operational efficiency during customer interactions.","Future iterations focus on deeper AI personalization, smarter contextual understanding, workflow-aware suggestions and tighter integration with broader AI copilot capabilities across the support ecosystem.")]),
])

QA['file'],QC['file']='quick-automations.html','quality-coach.html'
QA['next'],QC['next']=QC,QA
open('work/quick-automations.html','w').write(page(QA))
open('work/quality-coach.html','w').write(page(QC))
