import html
head=open('/tmp/head').read(); nav=open('/tmp/nav').read().replace('ROOT','../'); foot=open('/tmp/foot').read().replace('ROOT','../index.html')
def page(slug,title,desc,kicker,lede,meta,body,looks_h,caps):
    m=''.join(f'<div><span class="mono">{k}</span><b>{v}</b></div>' for k,v in meta)
    return f'''<!doctype html><html lang="en"><head>
{head}
<title>{title} — Kaushik Subramaniam</title><meta name="description" content="{html.escape(desc)}">
<link rel="stylesheet" href="../styles.css"></head><body>
<div class="shell">{nav}</div><main class="cs"><div class="wrap">
<div class="cs-hero"><a class="back rv" href="../index.html#work">← All work</a>
<div class="rv" style="margin-top:36px"><span class="mono">{kicker}</span></div>
<h1 class="rv" style="max-width:18ch">{title}</h1><p class="lede rv">{lede}</p>
<div class="meta rv">{m}</div><div class="cs-cover rv"><img src="../assets/{slug}.jpg" alt="{title} product screen"></div></div></div>
{looks(slug,title,looks_h,caps)}
<div class="wrap"><div class="read">{body}
</div></div></main>
{foot}
<script src="../main.js"></script></body></html>'''
def looks(slug,title,h,caps):
    n=len(caps)
    def fig(i,c,dup):
        hid=' aria-hidden="true"' if dup else ''
        alt='' if dup else title+': '+c
        return f'<figure class="wl-item"{hid}><span class="wl-img"><img src="../assets/screens/{slug}-{i}.jpg" alt="{alt}" loading="lazy"></span><figcaption><span>{i:02d} / {n:02d}</span>{c}</figcaption></figure>'
    one=''.join(fig(i,c,False) for i,c in enumerate(caps,1)); two=''.join(fig(i,c,True) for i,c in enumerate(caps,1))
    return f'<section class="wl rv" aria-label="What it looks like"><div class="wrap"><div class="read"><span class="mono">What it looks like</span><h2>{h}</h2></div></div><div class="wl-view"><div class="wl-track">{one}{two}</div></div></section>'
def sec(n,label,h,inner): return f'<section class="rv"><span class="mono">{label}</span><h2>{h}</h2>{inner}</section>'
P=lambda *ps:''.join(f'<p>{p}</p>' for p in ps)
cards=lambda cs:'<div class="cards">'+''.join(f'<div class="card"><h4>{a}</h4><p>{b}</p></div>' for a,b in cs)+'</div>'
hmw=lambda qs:'<ol class="hmw">'+''.join(f'<li>{q}</li>' for q in qs)+'</ol>'
checks=lambda xs:'<ul class="checks">'+''.join(f'<li>{x}</li>' for x in xs)+'</ul>'
metrics=lambda ms:'<div class="metrics">'+''.join(f'<div class="metric"><b>{a}</b><span>{b}</span></div>' for a,b in ms)+'</div>'
def matrix(q): return '<div class="matrix">'+''.join(f'<div class="{"hot" if hi else ""}"><span class="mono">{a}</span><p>{b}</p></div>' for a,b,hi in q)+'</div>'

twocol=lambda t1,a,t2,b:f'<div class="twocol"><div><h4>{t1}</h4><ol>'+''.join(f'<li>{x}</li>' for x in a)+f'</ol></div><div><h4>{t2}</h4><ol>'+''.join(f'<li>{x}</li>' for x in b)+'</ol></div></div>'
takeaways=lambda t,xs:f'<div class="take"><h4>{t}</h4>'+checks(xs)+'</div>'
edge=lambda xs:'<div class="edge"><h4>Our edge</h4><ul>'+''.join(f'<li>{x}</li>' for x in xs)+'</ul></div>'

qa_body=''.join([
sec('01','My role','Creating a foundation',P("I led the end-to-end design for Quick Automations, a real-time automation framework built specifically for conversational support workflows inside Freshdesk Omni.","From defining the information architecture to turning highly technical automation logic into approachable templates, I worked closely with Product, Engineering, CX and GTM teams to shape a scalable experience that could support omni-channel workflows without overwhelming admins.","The project became a foundational step toward Freshdesk's long-term workflow modernization vision.")),
sec('02','Problem statement','Built for email. Strained by chat.',P("Freshdesk's legacy automation framework was designed for email-first support. It relied heavily on <b>Hourly Triggers</b>, which evaluate tickets periodically instead of instantly. That worked for email, but it became a major operational limitation on conversational channels where customers expect replies in seconds. Teams couldn't reliably run:")+checks(["Instant acknowledgements","Delay-based customer reassurance","Smart fallback routing","Real-time follow-ups","Faster SLA-driven workflows","Multi-channel orchestration"])+P("Meanwhile Zendesk and Intercom already supported second-level conversational automation, making real-time execution a market expectation rather than a premium capability.")),
sec('03','How might we','Three questions, one north star.',hmw(["Help support teams automate real-time conversations without complex setup?","Execute automation rules within seconds instead of hours?","Simplify conversational automation for SMB admins while supporting omni-channel scale?"])),
sec('04','Research','Why the existing system kept falling short.',P("Before designing Quick Automations, I needed to understand why Freshdesk's existing framework struggled with conversational workflows. The findings validated the need for a dedicated real-time layer and showed how dramatically customer expectations had shifted.")+cards([("Email-first architecture","Tickets were evaluated periodically via Hourly Triggers. Reliable for email, but unfit for channels that demand instant responses."),("Expectations had changed","Research with <b>18 CX operations leads</b> showed <b>94%</b> of teams expected automated acknowledgements within 30–90 seconds on chat. Delays directly hurt CSAT and SLA."),("Delay & cancel became critical","Automations had to stop if an agent replied first. Existing systems lacked this, creating duplicate or irrelevant replies."),("Builders were too complex","Template setup averaged <b>2.3 minutes</b> vs <b>8.7</b> for builders, and errors dropped from 2.4 to 0.2 per setup."),("Speed beat flexibility","Teams consistently prioritized faster setup, execution and acknowledgement over highly customizable but complex workflow systems.")])+takeaways('Key takeaways',["Real-time channels require second-level automation responsiveness","Traditional automation models fail for conversational workflows","Delay-and-cancel execution is critical for chat-based support","Users preferred guided templates over complex workflow builders","Conversational automation needed a fundamentally different execution architecture"])),
sec('05','Deep dive into user behaviour',"Admins didn't want to build workflows.",P("Through stakeholder interviews, workflow analysis and operational mapping, one insight kept surfacing: conversational support teams behaved very differently from email-first teams. They needed instant fallback workflows, automated reassurance, fast setup and a single place to manage multi-channel automations.")+'<blockquote>“Admins didn\'t want to build workflows. They wanted the system to intelligently handle operational gaps automatically.”</blockquote>'+P("Email automations were treated as long-term process configuration. Conversational automations were expected to be set up and deployed within minutes, often during live support shifts. That pushed us to prioritize guided templates over fully customizable builders.")+twocol('Research objectives',["Understand operational gaps in conversational support workflows","Identify limitations in the existing automation system","Understand execution-speed expectations for real-time channels","Reduce setup complexity for SMB admins","Explore scalable patterns for future workflow unification"],'Key findings',["Customers expected automation to run within seconds, not minutes","The most urgent use cases were delayed responses and fallback routing","Existing automation felt too technical for SMB admins","Template-based setup significantly reduced onboarding friction","Real-time automation created immediate operational value","Multi-channel support made automation significantly more relevant"])),
sec('06','The 6 templates','Six high-frequency gaps. Six templates.',P("To simplify setup for SMB and mid-market admins, I designed Quick Automations around guided templates instead of asking users to configure workflows from scratch. Each template targets a high-frequency operational gap observed during research.")+cards([("Keep customers informed of delays","Sends reassurance messages when agents take longer than expected. Delay-and-cancel logic stops the message if an agent replies first."),("Reassign to available agent","Unassigns and reroutes conversations when the assigned agent doesn't respond in time, so chats never get stuck."),("Reroute to fallback group","Moves conversations to backup groups during peak load, helping teams keep SLA commitments through traffic spikes."),("Follow up with inactive customers","Nudges customers who stop responding mid-conversation, reviving stalled chats without manual effort."),("Reduce load for agents","Changes ticket status when customers stay inactive, clearing queues and freeing agents for fresh conversations."),("Keep track of resolution delays","Tags tickets that stay unresolved past a threshold, like <i>SLA risk</i> or <i>waiting_in_queue</i>, so teams can step in before resolution times slip.")])),
sec('07','Competitor analysis','A strategic bridge to real-time.',P("I analyzed conversational automation across Zendesk, Zoho, Salesforce and Intercom. Each offered powerful systems, but all relied on block-based builders that take extensive setup. Freshdesk had no modern builder yet, and Hourly Triggers couldn't meet 30-second SLAs. Quick Automations became the bridge from legacy email-first automation to real-time orchestration.")+cards([("Builders favoured flexibility over speed","Configuring even simple conversational workflows took multiple steps and technical understanding."),("Conversational support became the norm","WhatsApp, social DMs and web chat were growing much faster than email, raising the need for real-time tooling."),("SMB teams needed simpler automation","Existing systems were too complex for smaller teams, a clear opening for guided templates."),("Legacy automation was built for async","Periodic ticket evaluation was poorly suited to support where execution speed directly shapes CX.")])+edge(["Instant rule execution in as little as 30 seconds","Template-first conversational automation","Real-time delay-and-cancel workflows","Multi-channel support orchestration","Simplified setup for SMB admins"])),
sec('08','Action / Impact analysis','Mapping value against effort.',P("We mapped each automation opportunity on an Impact / Effort matrix to find the workflows with the highest operational value and the least setup friction, while flagging larger infrastructure work for the next phase of the workflow platform.")+matrix([("Easy wins · High impact, low effort","Instant acknowledgement replies, follow-ups with inactive customers",1),("Big bets · High impact, high effort","Template-based automation, delay-and-cancel logic, multi-channel auto-replies",1),("Incremental · Low impact, low effort","Template customization",0),("Money pit · Low impact, high effort","Fully customizable workflow builder",0)])+takeaways('Findings',["Simple conversational automations created the fastest operational impact, solving immediate pain without heavy configuration","High-frequency workflows like acknowledgements and inactive-customer follow-ups delivered more perceived value than advanced customization","The real-time engine and delay/cancel architecture were foundational for scaling workflows across omni-channel support"])),
sec('09','Features shipped','What we built.',cards([("Instant automation engine","A lightweight framework running workflows in as little as 30 seconds, architecturally separated from legacy Hourly Triggers for second-level reliability."),("Multi-channel quick automations","Configure once across WhatsApp, Facebook DM, Instagram DM and Web Chat, collapsing setup effort for omni-channel teams."),("Template-based setup","Guided templates for delays, reassignment, fallback routing, follow-ups and load reduction. Onboarding takes minutes, not afternoons."),("Delay & cancel logic","Automations halt the moment an agent responds, eliminating duplicate messages and conversational noise.")])),
sec('10','Measuring impact','The numbers.',metrics([("75%","of real-time channel customers configured Quick Automations"),("85%","coverage of eligible conversational workflows across channels"),("91%","reduction in dropped conversations via instant acknowledgements"),("$120K","feature-attributed MRR across 99 paid accounts")])+P("Beyond the metrics, Quick Automations laid the foundation for Freshdesk's unified <b>Workflows</b> platform, bringing real-time and asynchronous automation into one orchestration layer.")),
sec('11',"What's next",'A product is never finished.',P("Quick Automations was the first step in a broader workflow modernization effort. The long-term vision unifies legacy Automations and Quick Automations under a single Workflows platform that handles both asynchronous and real-time support automation.","The next phase focuses on richer automation actions, smarter execution, expanded orchestration and eventually a modern block-based builder, while keeping the simplicity and speed that made Quick Automations work for conversational support.")),
])
qc_body=''.join([
sec('01','My role','Creating a foundation',P("I designed the end-to-end experience for <b>Quality Coach</b>, an AI-powered assistance layer built directly into the agent reply composer.","The goal was to help support agents keep customer interactions high-quality in real time without disrupting their workflow. I worked closely with Product, AI, Engineering and CX stakeholders to surface AI feedback in context while keeping suggestions actionable rather than overwhelming.","A big part of the challenge was balancing proactive AI assistance with conversational flow, so agents still felt in control of their replies.")),
sec('02','Problem statement','Audited after the fact. Coached too late.',P("Support teams struggle to keep service quality consistent across large volumes of conversations, especially during high-pressure periods. Traditional QA relied on post-conversation audits, so feedback arrived after the interaction was already over. That created several gaps:")+checks(["Agents repeated avoidable mistakes","Quality feedback arrived too late","QA teams spent excessive time auditing manually","Service quality varied significantly between agents","Managers lacked real-time visibility into quality","Coaching loops never closed during live shifts"])+P("Support teams needed a proactive quality system that could help agents improve conversations while they were actively replying.")),
sec('03','How might we','Three questions, one north star.',hmw(["Help support agents improve conversation quality in real time without disrupting live customer interactions?","Reduce dependency on post-conversation audits through proactive AI assistance?","Surface contextual AI feedback without overwhelming agents during live conversations?"])),
sec('04','Research','Why traditional QA kept missing the moment.',P("I wanted to understand how support teams handled quality assurance and where inefficiencies crept into their workflows. The research covered agent behaviour during live conversations, post-conversation QA, feedback fatigue, AI-assisted writing and expectations for real-time coaching.")+cards([("Traditional QA was reactive","Quality systems evaluated conversations after they ended. Audits surfaced patterns but rarely helped in the moment mistakes happened."),("Agents struggled at peak volume","Tone, grammar and compliance slipped across parallel chats. The issue wasn't knowledge, it was cognitive overload."),("Too much feedback created friction","Agents quickly ignored excessive or intrusive suggestions. Concise, contextual feedback outperformed long-form correction."),("Managers lacked live visibility","QA managers only spotted patterns after conversations finished. Teams needed live operational visibility, not just retrospective analysis."),("AI had to feel collaborative","Agents preferred assistive AI to autonomous AI. They wanted suggestions while still owning the final reply, a foundational principle for the design.")])+takeaways('Key takeaways',["Quality improvement needed to happen during conversations, not after","Lightweight contextual suggestions beat intrusive AI interventions","Cognitive overload was a bigger problem than lack of training","Real-time coaching meaningfully reduced repetitive QA effort","AI worked best when agents kept ownership of the response"])),
sec('05','Deep dive into user behaviour',"Agents didn't want another reviewer.",P("Through workflow analysis, stakeholder discussions and support interaction reviews, clear patterns emerged. Agents focused heavily on speed and resolution, unintentionally overlooking tone, grammar and clarity during busy periods. QA managers spent significant time auditing conversations after the fact while the same issues kept repeating.")+'<blockquote>“Agents didn\'t want another tool to review them. They wanted intelligent assistance that helped them respond better without interrupting their flow.”</blockquote>'+P("That insight is why Quality Coach lives inside the reply composer rather than in a separate review interface.")+twocol('Research objectives',["Understand operational gaps in traditional QA workflows","Identify moments where agents commonly make mistakes","Reduce cognitive overload during conversations","Explore how AI suggestions could feel contextual instead of intrusive","Improve conversation quality without increasing handling time"],'Key findings',["Real-time guidance was far more valuable than post-conversation feedback","Concise suggestions performed better than long-form AI corrections","Agents preferred contextual inline recommendations","QA managers wanted visibility into coaching effectiveness","Quality improved when AI feedback was actionable and immediate"])),
sec('06','Solution overview','An assistance layer, not an audit tool.',P("Quality Coach added a proactive AI assistance layer directly inside the agent reply experience. It continuously evaluates replies as they're written and surfaces suggestions across seven dimensions, each of which the agent can apply instantly or ignore. Agents stay in control while still getting AI-powered coaching.")+'<ol class="dims">'+''.join(f'<li><span>{i:02d}</span>{d}</li>' for i,d in enumerate(["Grammar","Tone","Sentence length","Profanity","Relevancy","Filler words","Spelling"],1))+'</ol>'),
sec('07','Competitor analysis','A coaching layer no one else built.',P("I analyzed conversational quality and AI assistance across Intercom, Zendesk, Salesforce Service Cloud, Grammarly Business and Kore.ai. Most platforms either focused on post-conversation QA reviews or offered generic writing help disconnected from support workflows. Very few embedded contextual coaching directly inside the reply experience.")+cards([("A shift to AI-assisted operations","CX organizations expected AI to proactively improve agent productivity and quality, not just act as passive analytics."),("QA teams were overwhelmed","Manual audits scaled poorly as conversation volumes grew, putting pressure on quality managers."),("Real-time had stronger behavioural impact","Immediate feedback drove higher correction rates than delayed, audit-based coaching across every cohort we studied."),("AI needed to stay assistive","Agents responded better to collaborative AI that enhanced replies instead of replacing them.")])+edge(["Real-time contextual AI coaching","Inline conversational quality analysis","Lightweight assistive suggestions","Actionable feedback over generic scoring","Embedded composer experience"])),
sec('08','Action / Impact analysis','Mapping coaching opportunities.',P("We mapped coaching opportunities on an Impact / Effort framework to find which AI interventions improved conversation quality the most without disrupting agents during live interactions.")+matrix([("Easy wins · High impact, low effort","Inline grammar correction, filler-word reduction",1),("Big bets · High impact, high effort","Real-time tone and profanity analysis, contextual relevancy engine",1),("Incremental · Low impact, low effort","Overall reply score, partial-resolve suggestions",0),("Money pit · Low impact, high effort","Auto-rewriting full replies, mandatory AI approval gating",0)])+takeaways('Key takeaways',["Lightweight inline coaching drove far better adoption than disruptive review-based systems","Contextual suggestions improved agent confidence without adding cognitive load","Real-time intervention cut repeat quality issues before conversations ever reached QA audits"])),
sec('09','Features shipped','What we built.',cards([("Real-time quality coaching","Continuously analyzes replies during live conversations and surfaces quality recommendations before the message is sent."),("Contextual inline suggestions","Tone, grammar, profanity, sentence length, relevancy and spelling suggestions appear right inside the composer."),("Actionable AI corrections","Each suggestion can be applied in one tap or dismissed, so the agent always owns the reply."),("QA visibility & analytics","Managers see coaching adoption and quality trends across agents, without waiting for audits.")])),
sec('10','Measuring impact','The numbers.',metrics([("62%","reduction in repeated grammar, tone & profanity issues across agents"),("47%","drop in time QA teams spent manually auditing routine conversations"),("+18 pts","CSAT lift during high-volume shifts with Quality Coach active"),("92%","of agents kept Quality Coach on after the first two-week trial")])+P("Analytics also showed customer sentiment stayed closer to positive in conversations handled with Quality Coach.","Beyond the metrics, it laid the foundation for Freshdesk Omni's broader AI copilot vision, combining real-time coaching, conversational intelligence and QA visibility in one assistive layer.")),
sec('11',"What's next",'A product is never finished.',P("Quality Coach was an early foundational layer for AI-assisted support inside Freshdesk Omni. The long-term vision goes beyond grammar and tone toward fully contextual conversational intelligence that proactively improves resolution quality, compliance, empathy and efficiency.","Future iterations focus on deeper personalization, smarter contextual understanding, workflow-aware suggestions and tighter integration with AI copilot capabilities across the support ecosystem.")),
])
open('work/quick-automations.html','w').write(page('qa','Quick Automations',"Real-time automation for conversational support in Freshdesk Omni.",'Freshdesk Omni · 0→1 · 2025',"An instant automation framework built for conversational support inside Freshdesk, executing workflows in as little as 30 seconds across WhatsApp, Web Chat, Facebook DM and Instagram DM.",[("Project type","0→1 product experience"),("Role","Research · Product Thinking · UX Strategy · UI/UX"),("Surface","Freshdesk Omni"),("Year","2025")],qa_body,'Quick Automations, up close.',["Quick Automations home","Multi-channel setup","Template gallery","Rule configuration","Rule enablement"]))
open('work/quality-coach.html','w').write(page('qc','Quality Coach',"Real-time AI coaching inside the Freshdesk Omni reply composer.",'Freshdesk Omni · AI-first CX · 2024',"An AI-powered real-time coaching system inside Freshdesk Omni that helps support agents improve grammar, tone and clarity while they're replying to customers.",[("Project type","AI-first CX experience"),("Role","Research · Product · UX/UI"),("Surface","Freshdesk Omni"),("Year","2024")],qc_body,'Inside the composer.',["Live coaching","Profanity correction","Grammar correction","All errors","Usage analytics"]))
